language: node_js
node_js:
- 14.13.0
script:
  - echo '********** Build Start *********'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running Tests'
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: jceIGXY6aRD1CV/cxy7P1HZUr1UZ3B3YMS14WI3946JwkfH0FSKt0Bi3h6GWYzzjRvrEEC4asnkYC2xVlc4pB8yGgUz/2v50P8SXwtIlyuFBj0pHq15UY9hxGGvkPrSQMHWFLby+nZdol4c5xPSYNpb2Tcdq+Aghe2Sl3j3xkY25FzCIVXlrK9yD9jdoL9wUhI1UGyj9+h7T7qnBzPhDjJpkrgGn8AsVXA+FZXTmgU6J4c+Uv9dyZ/fiqilmBVULlG9h/Xb1FVzW+qIT2bazqx7Rnv3xXAoLV2YqTqww+vqmGs1jl5iqRVIiIptW4LzVtyAlP2+e1wO3ELDVG8CtbcQ5dyb43LbaWHqKEfoC7qDz2iqQ7eLnRzuMT3dv+Q4xEU4pduWyyBoaCV2KuioSFZUaDaq9VKg7LgaeG+LKlGJvXdp5pELgdzclmIIS4LVxAEEm3RZp8xQk2CVWKptFinCL6QSE78pRDA3Sx2sS2PqTws8JmwPZwb3JSv6PzqhaWABWk8y2BsF3ApGtVa0QEZoZQxUhEMSpcaSLzQyjcIXl+vjf9D1dnH1kIrUMdvvyrVz/lCgeVOZRk+3oGNQwNF5SeyGKI9A6BQYeX/7Z/clHHkMpI4YJ6P4ajp1EjEf6vlxqCVgg6d4XB/R82CPRJlguy3jA0EjW90Ly1wjyBXA=
  app: petitioner
  on:
    repo: BritishCounterpart/petitioner
  skip_cleanup: 'true'
