language: node_js
node_js:
- 14.13.0
deploy:
  api_key:
    secure: seTr2ULmCRFqhtLiKvsr066o4/DEnQ/4qSBQW16RQc7kVexYmyQxQVoOEwwfDYkM2hO3yykCPZxEFjNLbwh1U4cVmfEmDAfApsqFM5UiYQkUGa553KkVsDcSoVV/ZWgOFRv3EDKfdvJ7KTT0udepyoIXvpiKvMymbKjCgGK/3jSr490Ucj2ViX8ae3e7O5FBchkJ0cySF+qs9JQH6Hw+pEmcMD2OE7dCE2a3DucMu9nON/PpTKYqWvhDJQfY6bk9rWJ40w6UdxRDWAYp45EjqhhlWa2UgEhqqVBH44KxgdjiWDE/MV007fKVU3SonVkoJM4eFsDVYcGWDIYqO9C2J+/QHTbROTkQ5bWgka0fkc8de0bLxpaBIoLG2x+YaHzNZvCZZm05dScyZzXBEkHX9+iWQ+Nc+Ap4JX5DAI0EIPKYqP8BqgZR15gFlgCjdixR2mFkeoptP4a5Ecbk5LJ/So3KsXw/PlwGVSH5K3Y7vkih4EhHVKbpGtVGFvzwowYgmcelSNO/OKF2Dy/jZwma9Pu8TdBsYkl7dzaTuBPyod+6gfG72IAX7XAvAHAoVhOcUsDUPa9nhGspCkIh4vCs/MxWUCb3DN9VBVcZD/TNsBqQ0YW2peADDupYcpDjGIuojO3w/OnGIQ5Q98hNBKH7D7spx5oPGz4R94bhbNqEhVs=
