language: node_js
node_js:
- 14.13.0
script:
- echo '********** Build Start *********'
- echo 'Installing Dependencies'
- npm install
- echo 'Running Tests'
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: ZEwsvM+6QAfryXnq6tHWCNExOfAQgDvTnL34t+9qfRIRCd7QW5OYihnqgC9yrtdXFaKxb8MHkBdZJdW0q5qXnx9n0GiEdjGSVsh+mbQVrcr40I6zHeihvC/K6pq05UF8dHz9vHqst26CdFLWlWJlBAnjYviEqVVvD2XEL4s5zMYgiuZ3/lGrTQxDtZ1LQE747+5ACWXa5fB0cioqrMAo0E2oJ+eHfN6HDcWvTq/Agr1VHb/zGIpUl+v49gjLHxo29MmXB2IPP487RIb8vkqPd9Q568Xw6ZtBuKsZMEZUYK88jn+tG72iFgycq7rAM/3OKJQ0qXUcvo92qEyMuQr6zesbOq4Oxgl/DKHvCW0zOMPHoSjWTMRnAAUM9q3bDzbXiYQow7rE6oCzGTZSxbYeDye1fyLFT5qty9EV9L/qtfHibEXE6NJBZA3tkOCjEUc7TCf1Z1V2I/pfV1CkzK8AcuOnvyfIkKV9R1sSLS70fRUOZTBWFMmGsI0/13iSFO3sTN/hSiNQal4n+WYc5Ss+0/BYpbcUckn6QFUWd7bbH7um0DghlKWUvM3sQ2nREqKUfdqyLnho5A7Pwei9Hm7K8vaPtSNEczhtrZVsApPXU63PpUoDyKIsktBknfVqMA/21inTnKcN1/zRmnxbHhQd5ebkFjD4+peIX/tCOFL2Gmk=
  app: petitioner
  on:
    repo: BritishCounterpart/petitioner
  skip_cleanup: 'true'
